scoop install 7zip
scoop install clangd
scoop install cmake
scoop install cppcheck
scoop install dark
scoop install elixir
scoop install erlang
scoop install gdb
scoop install git
scoop install imagemagick
scoop install innounp
scoop install luacheck
scoop install lua-language-server
scoop install mariadb
scoop install msys2
scoop install neovim
scoop install nodejs
scoop install oh-my-zsh
scoop install postgresql17
scoop install pwsh
scoop install python313
scoop install ruby34
scoop install winmerge
